# Generated by Django 4.2.2 on 2023-07-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
